apiVersion: v1
entries:
  cluster-components-operator:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2020-08-04T05:22:13.823122966Z"
    dependencies:
    - condition: istioOperator.install
      name: istio-operator
      repository: ""
    description: A Helm chart for managing various cluster level components as operators
    digest: 1d26c72995c665c28560adff5f8af14c27725dd5a798842bebeae48dd4f6e49c
    name: cluster-components-operator
    type: application
    urls:
    - https://lucidprogrammer.github.io/k8s-cluster-components/chart/cluster-components-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-04T05:22:13.822053564Z"
