# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apps.cluster.components_certificatemanagers.yaml
- bases/apps.cluster.components_clusterautoscalers.yaml
- bases/apps.cluster.components_verticalpodautoscalers.yaml
- bases/apps.cluster.components_externaldns.yaml
- bases/apps.cluster.components_metricservers.yaml
- bases/apps.cluster.components_route53nestedsubdomains.yaml
- bases/apps.cluster.components_clusternamedistioingresses.yaml
#+kubebuilder:scaffold:crdkustomizeresource
