# permissions for end users to view certificatemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificatemanager-viewer-role
rules:
- apiGroups:
  - apps.cluster.components
  resources:
  - certificatemanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cluster.components
  resources:
  - certificatemanagers/status
  verbs:
  - get
