# permissions for end users to view clusterautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterautoscaler-viewer-role
rules:
- apiGroups:
  - apps.cluster.components
  resources:
  - clusterautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cluster.components
  resources:
  - clusterautoscalers/status
  verbs:
  - get
