# permissions for end users to view clusternamedistioingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusternamedistioingress-viewer-role
rules:
- apiGroups:
  - apps.cluster.components
  resources:
  - clusternamedistioingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cluster.components
  resources:
  - clusternamedistioingresses/status
  verbs:
  - get
