# permissions for end users to view metricservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricserver-viewer-role
rules:
- apiGroups:
  - apps.cluster.components
  resources:
  - metricservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cluster.components
  resources:
  - metricservers/status
  verbs:
  - get
