# permissions for end users to view route53nestedsubdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route53nestedsubdomain-viewer-role
rules:
- apiGroups:
  - apps.cluster.components
  resources:
  - route53nestedsubdomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cluster.components
  resources:
  - route53nestedsubdomains/status
  verbs:
  - get
