apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: cluster-components-operator
    chart: '{{ include "cluster-components-operator.chart" . }}'
    heritage: Helm
    release: '{{ .Release.Name }}'
  name: verticalpodautoscalers.cluster.components
spec:
  group: cluster.components
  names:
    kind: VerticalPodAutoscaler
    listKind: VerticalPodAutoscalerList
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}

---