apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-components-operator
    chart: '{{ include "cluster-components-operator.chart" . }}'
    heritage: Helm
    release: '{{ .Release.Name }}'
  name: cluster-components
  namespace: cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-components
  template:
    metadata:
      labels:
        name: cluster-components
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          value: ''
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: cluster-components
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: ANSIBLE_VERBOSITY_CLUSTERAUTOSCALER_CLUSTER_COMPONENTS
          value: '4'
        image: lucidprogrammer/cluster-components-operator:{{.Values.imageTag}}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 3
        name: cluster-components
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
      serviceAccountName: cluster-components-operator
      volumes:
      - emptyDir: {}
        name: runner

---