apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cluster-components-operator
    chart: '{{ include "cluster-components-operator.chart" . }}'
    heritage: Helm
    release: '{{ .Release.Name }}'
  name: cluster-components-operator
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---