apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cluster-components-operator
    chart: '{{ include "cluster-components-operator.chart" . }}'
    heritage: Helm
    release: '{{ .Release.Name }}'
  name: cluster-components-operator
  namespace: cluster-operator

---