---
- name: "is clusterissuers crd available"
  set_fact:
    clusterissuer_available: "{{lookup('k8s', kind='CustomResourceDefinition',resource_name='clusterissuers.cert-manager.io')}}"

- name: "remove cluster issuer"
  when:
    - state == 'absent'
    - clusterissuer_available | length > 0
  community.kubernetes.k8s:
    state: "absent"
    definition: "{{ lookup('template','cluster-issuer.yaml' | from_yaml )}}"
- name: "install cert-manager"
  community.kubernetes.helm:
    chart_ref: cert-manager
    chart_repo_url: https://charts.jetstack.io
    chart_version: v0.15.1
    release_name: cert-manager
    release_namespace: cert-manager
    release_state: "{{ state }}"
    release_values:
      installCRDs: true
- name: "create cluster issuer"
  when: state == 'present'
  community.kubernetes.k8s:
    state: "{{ cluster_issuer.state }}"
    definition: "{{ lookup('template','cluster-issuer.yaml' | from_yaml )}}"
  
