apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-{{ external_dns_cr_name }}
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-{{ external_dns_cr_name }}
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
{% if ingress_class == 'istio' %}
- apiGroups: ["networking.istio.io"]
  resources: ["gateways"]
  verbs: ["get","watch","list"]
{% endif %}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer-{{ external_dns_cr_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-{{ external_dns_cr_name }}
subjects:
- kind: ServiceAccount
  name: external-dns-{{ external_dns_cr_name }}
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-{{ external_dns_cr_name }}
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-{{ external_dns_cr_name }}
  template:
    metadata:
      labels:
        app: external-dns-{{ external_dns_cr_name }}
    spec:
      serviceAccountName: external-dns-{{ external_dns_cr_name }}
      nodeSelector: {{ nodeSelector }}
      containers:
      - name: external-dns-{{ external_dns_cr_name }}
        image: us.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.7.6
        args: {{external_dns_args}}
---