apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusternamedistioingresses.cluster.components
spec:
  group: cluster.components
  names:
    kind: ClusterNamedIstioIngress
    listKind: ClusterNamedIstioIngressList
    plural: clusternamedistioingresses
    singular: clusternamedistioingress
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
