apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: metricservers.cluster.components
spec:
  group: cluster.components
  names:
    kind: MetricServer
    listKind: MetricServerList
    plural: metricservers
    singular: metricserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
