---
# vars file for externaldns

external_dns_args:
  - --source=service
  - --source=ingress
  - --source=istio-gateway
  - --provider=aws
  - --policy=sync
  - --log-level=debug
  - --aws-zone-type=public