---
# vars file for externaldns
external_dns_istio_args:
  - --source=service
  - --source=istio-gateway

external_dns_args:
  - --source=ingress
  - --policy=sync
  - --log-level=debug
  - --aws-zone-type=public
  - --registry=txt