apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: "{{cluster_issuer.name}}"
spec:
  acme: 
    email: "{{cluster_issuer.acme.email}}"
    server: "{{cluster_issuer.acme.server}}"
    privateKeySecretRef:
      name: "{{cluster_issuer.name}}"
    solvers: {{solvers}}